// POST
export const FETCH_ALL_POST = 'FETCH_ALL_POST'
export const CREATE_POST = 'CREATE_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const DELETE_POST = 'DELETE_POST'
export const LIKE_POST = 'LIKE_POST'


// AGREGAR PRODUCTO
// export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO'
// export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO'
// export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR'