// LOADING
export const LOADING = "LOADING"
export const LOADING_EXITO = "LOADING_EXITO"

// POST
export const FETCH_ALL_POST = 'FETCH_ALL_POST'
export const CREATE_POST = 'CREATE_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const DELETE_POST = 'DELETE_POST'
export const LIKE_POST = 'LIKE_POST'

// AUTH
export const AUTH_GOOGLE = 'AUTH_GOOGLE'
export const AUTH_SIGNIN = 'AUTH_SIGNIN'
export const AUTH_SIGNUP = 'AUTH_SIGNUP'

export const LOGOUT_LOADING = 'LOGOUT_LOADING'
export const LOGOUT = 'LOGOUT'


// AGREGAR PRODUCTO
// export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO'
// export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO'
// export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR'